vtc_did = "did:webvh:QmbWdMjJ2zXTYTE91nR4KQDupgDBrs7dWVkapzNMg33NoV:webvh.vtc.storm.ws:vtc"
vta_did = "did:webvh:Qmf9XfaKSP5TyU1CLniMZjyEzLN9MsFyBfkBZdvFVseSiD:webvh.vtc.storm.ws:vta"
vtc_name = "OpenVTC"
vtc_description = "First Community"
public_url = "https://vtc.storm.ws/"

[server]
host = "0.0.0.0"
port = 8200

[log]
level = "info"
format = "text"

[store]
data_dir = "data/vtc"

[messaging]
mediator_url = ""
mediator_did = "did:webvh:QmYtgpvHLu4rCBDur2PbWcfHCCBS6wXdyNvfMdbVsR7C6m:webvh.vtc.storm.ws:mediator"

[auth]
access_token_expiry = 900
refresh_token_expiry = 86400
challenge_ttl = 300
session_cleanup_interval = 600
jwt_signing_key = "nQUmJTG8p14IJm2ifeHxCgjW-dr8m3zreP5gIysQ9Y0"

[secrets]
keyring_service = "vtc"
