vta_did = "did:webvh:QmavpC6Z6NsDXwM4moMiitS8YsxTgRNzX9b3AtoKJSXvFi:webvh.vtc.storm.ws:local-vta"
vta_name = "GG Local VTA"
public_url = "http://localhost:8100"

[server]
host = "0.0.0.0"
port = 8100

[log]
level = "info"
format = "text"

[store]
data_dir = "data/vta"

[messaging]
mediator_url = ""
mediator_did = "did:webvh:QmYtgpvHLu4rCBDur2PbWcfHCCBS6wXdyNvfMdbVsR7C6m:webvh.vtc.storm.ws:mediator"

[services]
rest = true
didcomm = true

[auth]
access_token_expiry = 900
refresh_token_expiry = 86400
challenge_ttl = 300
session_cleanup_interval = 600
jwt_signing_key = "QLAwARhehsmYuG3sbOPnMjMbizOKzYQ0Hf4vZzqp_aM"

[secrets]
keyring_service = "vta"
